train:
  mode: "jax" # torch or jax
  model: "sovits"
  seed: 1234
  epochs: 10000
  learning_rate: 2e-5
  betas: [0.95, 0.98]
  lr_decay: 0.999875
  total_steps: 30 # base on dataset size
  eps: 1e-9
  batch_size: 8
  c_stft: 9
  c_mel: 1.
  c_kl: 0.2
  port: 8001
  pretrain: ""
#############################
data: 
  training_files: "files/train.txt"
  validation_files: "files/valid.txt"
  segment_size: 8000  # WARNING: base on hop_length
  max_wav_value: 32768.0
  sampling_rate: 44100
  filter_length: 2048
  hop_length: 512
  win_length: 2048
  mel_channels: 100
  mel_fmin: 50.0
  mel_fmax: 16000.0
#############################
log:
  info_interval: 100
  eval_interval: 100
  save_interval: 100
  num_audio: 6
  pth_dir: 'chkpt'
  log_dir: 'logs'
model:
  type: 'Naive'
  n_layers: 3
  n_chans: 256
  use_pitch_aug: true  
  n_spk: 1 # max number of different speakers
Gaussian: 
  loss: 'l1'
  timesteps: 1000
  sampling_timesteps: 1000
  objective: 'predict_noise'
  beta_schedule: 'cosine'
  #min_snr_loss_weight: True,
  #scale_shift: True,
  scale_factor: 0.25
  noise_type: 'normal'
  self_condition: True
